import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaMigration1756989566695 implements MigrationInterface {
    name = 'SchemaMigration1756989566695'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_a23208dae7d5405e42c49e661a7"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`CREATE TABLE "regions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "districts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "region_id" uuid NOT NULL, CONSTRAINT "PK_972a72ff4e3bea5c7f43a2b98af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "white_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" text NOT NULL, "pin" character varying(50), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_used_at" TIMESTAMP WITH TIME ZONE, "is_revoked" boolean NOT NULL DEFAULT false, "ip_address" character varying(45), "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_7cfc33996030d6dc54e604d9117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_050211c2add56219896d3593d1" ON "white_token" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "verification_tokens" ("id" SERIAL NOT NULL, "token" character varying(25), "reasons" text NOT NULL DEFAULT '[*]', "expire_at" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'Active', "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2d4d7a2aa57ef199e61567db22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "device_info"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "last_seen_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "oauthClientId"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_units" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "property_units" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_units" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "party_contacts" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "party_contacts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "party_contacts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payment_providers" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "mandates" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "parties" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "lease_charges" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "billing_runs" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "leases" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "region_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "district_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "glc_number" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verified_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mobile" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "two_factor_enabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "two_factor_pin" character varying(6)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_first_time" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "town" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "region_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "district_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "time_in" character varying(13)`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "time_out" character varying(13)`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "token" text`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "refresh_token" text`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "payload" text`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "last_activity" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "revoked_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "revoked_by" bigint`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "job_links" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "job_links" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "job_links" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dunning_events" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "dunning_rules" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "adjustments" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "districts" ADD CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_4cf5c9d5e17d02dcd75ee26dbfc" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_b61dcfd1fe20c84397b07551564" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "white_token" ADD CONSTRAINT "FK_050211c2add56219896d3593d1b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_efc03fc2a5902ef17fb8a2bdcc2" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_efc03fc2a5902ef17fb8a2bdcc2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1901e9aae03c8897b7dd460c27f"`);
        await queryRunner.query(`ALTER TABLE "white_token" DROP CONSTRAINT "FK_050211c2add56219896d3593d1b"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_b61dcfd1fe20c84397b07551564"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_4cf5c9d5e17d02dcd75ee26dbfc"`);
        await queryRunner.query(`ALTER TABLE "districts" DROP CONSTRAINT "FK_4271e8e205bbdce31975c55ed3f"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "ip_address" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_a000cca60bcf04454e727699490"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(32)`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "adjustments" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "dunning_rules" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "dunning_events" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "job_links" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "job_links" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "job_links" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "revoked_by"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "revoked_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "last_activity"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "payload"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "time_out"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "time_in"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "district_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "region_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "town"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_first_time"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "two_factor_pin"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "two_factor_enabled"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mobile"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verified_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "glc_number"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "district_id"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "region_id"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "leases" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "billing_runs" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "lease_charges" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "mandates" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "payment_providers" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "party_contacts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "party_contacts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "party_contacts" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "property_units" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "property_units" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_units" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "oauthClientId" uuid`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "last_seen_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "device_info" jsonb`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "district" character varying(128) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "region" character varying(128) NOT NULL`);
        await queryRunner.query(`DROP TABLE "verification_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_050211c2add56219896d3593d1"`);
        await queryRunner.query(`DROP TABLE "white_token"`);
        await queryRunner.query(`DROP TABLE "districts"`);
        await queryRunner.query(`DROP TABLE "regions"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_a23208dae7d5405e42c49e661a7" FOREIGN KEY ("oauthClientId") REFERENCES "oauth_clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
