import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaMigration1756903418708 implements MigrationInterface {
    name = 'SchemaMigration1756903418708'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpoint_url" character varying(512) NOT NULL, "secret" character varying(512), "active" boolean NOT NULL DEFAULT true, "description" text, CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_events_status_enum" AS ENUM('PENDING', 'DELIVERED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "webhook_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_type" character varying(128) NOT NULL, "payload" jsonb NOT NULL, "status" "public"."webhook_events_status_enum" NOT NULL DEFAULT 'PENDING', "last_attempt_at" TIMESTAMP WITH TIME ZONE, "attempt_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "webhookId" uuid NOT NULL, CONSTRAINT "PK_4cba37e6a0acb5e1fc49c34ebfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."property_units_status_enum" AS ENUM('AVAILABLE', 'LEASED', 'UNAVAILABLE')`);
        await queryRunner.query(`CREATE TABLE "property_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unit_code" character varying(128) NOT NULL, "description" text, "area_sqm" numeric, "status" "public"."property_units_status_enum" NOT NULL DEFAULT 'AVAILABLE', "propertyId" uuid, CONSTRAINT "PK_c7d7d8f633643123e9f9e0a0c83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5fb0cc1f34e30369e6226bef5a" ON "property_units" ("unit_code") `);
        await queryRunner.query(`CREATE TYPE "public"."documents_owner_type_enum" AS ENUM('PROPERTY', 'LEASE', 'INVOICE', 'PAYMENT', 'MANDATE', 'PARTY')`);
        await queryRunner.query(`CREATE TABLE "documents" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_type" "public"."documents_owner_type_enum" NOT NULL, "owner_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "mime_type" character varying(128) NOT NULL, "storage_url" text NOT NULL, "uploadedById" uuid, "propertyId" uuid, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_888a4852e27627d1ebd8a094e9" ON "documents" ("owner_id") `);
        await queryRunner.query(`CREATE TABLE "party_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "phone" character varying(32), "email" character varying(255), "is_primary" boolean NOT NULL DEFAULT false, "partyId" uuid, CONSTRAINT "PK_fdfcdfdbce28e610e1cfe7ed878" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_type_enum" AS ENUM('MOMO', 'CARD', 'BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_provider_enum" AS ENUM('MTN', 'TELECEL', 'AT', 'VISA')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."payment_methods_type_enum" NOT NULL, "provider" "public"."payment_methods_provider_enum", "masked_account" character varying(128), "token" character varying(512), "expiry_date" date, "is_default" boolean NOT NULL DEFAULT false, "status" "public"."payment_methods_status_enum" NOT NULL DEFAULT 'ACTIVE', "partyId" uuid, CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('MOMO', 'CARD', 'BANK', 'CASH')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_channel_enum" AS ENUM('MOBILE_APP', 'WEB_APP', 'BACKOFFICE', 'AUTOPAY', 'FIELD_POS')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SETTLED', 'FAILED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "method" "public"."payments_method_enum" NOT NULL, "channel" "public"."payments_channel_enum" NOT NULL, "currency" character varying(8) NOT NULL, "amount" numeric NOT NULL, "fees" numeric, "net_amount" numeric NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "external_txn_id" character varying(255), "txn_time" TIMESTAMP WITH TIME ZONE NOT NULL, "remarks" text, "providerId" uuid, "payerPartyId" uuid, "receiverOrgUnitId" uuid, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0942ab806143ef6a2c888dce03" ON "payments" ("external_txn_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reconciliation_lines_match_status_enum" AS ENUM('MATCHED', 'UNMATCHED', 'MULTIPLE')`);
        await queryRunner.query(`CREATE TABLE "reconciliation_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "external_txn_id" character varying(255) NOT NULL, "amount" numeric NOT NULL, "txn_time" TIMESTAMP WITH TIME ZONE NOT NULL, "match_status" "public"."reconciliation_lines_match_status_enum" NOT NULL DEFAULT 'UNMATCHED', "reconciliationId" uuid, "matchedPaymentId" uuid, CONSTRAINT "PK_09ad4523a3b76ca30c8c022161f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reconciliations_status_enum" AS ENUM('IMPORTED', 'PARTIAL', 'MATCHED', 'MISMATCH')`);
        await queryRunner.query(`CREATE TABLE "reconciliations" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_name" character varying(255) NOT NULL, "file_date" date NOT NULL, "status" "public"."reconciliations_status_enum" NOT NULL DEFAULT 'IMPORTED', "providerId" uuid NOT NULL, CONSTRAINT "PK_110f3839ca29e2fd8ff4aaec7b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_providers" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(64) NOT NULL, "display_name" character varying(128) NOT NULL, "config" jsonb, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1e51e9c9553171a6d1a3c46f3a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3b92bdeea5c610e84052154ef2" ON "payment_providers" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."mandates_status_enum" AS ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "mandates" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "external_ref" character varying(255), "status" "public"."mandates_status_enum" NOT NULL DEFAULT 'PENDING', "max_amount" numeric, "start_date" date NOT NULL, "end_date" date, "consent_captured_at" TIMESTAMP WITH TIME ZONE NOT NULL, "partyId" uuid, "paymentMethodId" uuid, "providerId" uuid, CONSTRAINT "PK_08c57882cd87cc778f329700004" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."parties_type_enum" AS ENUM('PERSON', 'ORGANIZATION')`);
        await queryRunner.query(`CREATE TABLE "parties" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."parties_type_enum" NOT NULL, "legal_name" character varying(255) NOT NULL, "ghana_card_no" character varying(32), "tin_no" character varying(64), "email" character varying(255), "phone" character varying(32), "billing_address" jsonb, CONSTRAINT "PK_da698299dca60d55f0050dde935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_109010e7cbb22421bb4bf32b94" ON "parties" ("ghana_card_no") `);
        await queryRunner.query(`CREATE INDEX "IDX_79a3477ecd27e3364b4c23f298" ON "parties" ("tin_no") `);
        await queryRunner.query(`CREATE TYPE "public"."lease_charges_frequency_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "lease_charges" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "amount" numeric NOT NULL, "is_recurring" boolean NOT NULL DEFAULT false, "frequency" "public"."lease_charges_frequency_enum", "start_date" date NOT NULL, "end_date" date, "taxable" boolean NOT NULL DEFAULT false, "tax_code" character varying(64), "leaseId" uuid, CONSTRAINT "PK_e163963165ef1afff1388031d62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."billing_runs_run_type_enum" AS ENUM('AUTOMATIC', 'MANUAL')`);
        await queryRunner.query(`CREATE TABLE "billing_runs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_type" "public"."billing_runs_run_type_enum" NOT NULL, "run_at" TIMESTAMP WITH TIME ZONE NOT NULL, "scheduled_for" date, "notes" text, "orgUnitId" uuid NOT NULL, "initiatedById" uuid, CONSTRAINT "PK_6cbc5e20856bf81be0e61423167" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "line_no" integer NOT NULL, "description" character varying(512) NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, "line_total" numeric NOT NULL, "tax_amount" numeric, "invoiceId" uuid, CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_no" character varying(128) NOT NULL, "invoice_date" date NOT NULL, "due_date" date NOT NULL, "currency" character varying(8) NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "subtotal" numeric NOT NULL, "tax_total" numeric, "total" numeric NOT NULL, "balance" numeric NOT NULL, "notes" text, "billingRunId" uuid, "leaseId" uuid, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_37669c562a2525929927d9d691" ON "invoices" ("invoice_no") `);
        await queryRunner.query(`CREATE TYPE "public"."leases_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'SUSPENDED', 'TERMINATED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."leases_frequency_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "leases" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lease_number" character varying(128) NOT NULL, "status" "public"."leases_status_enum" NOT NULL DEFAULT 'DRAFT', "start_date" date NOT NULL, "end_date" date NOT NULL, "base_currency" character varying(8) NOT NULL, "base_rent" numeric NOT NULL, "frequency" "public"."leases_frequency_enum" NOT NULL, "next_bill_date" date, "security_deposit" numeric, "escalation_percent" numeric, "late_fee_percent" numeric, "billing_day_of_month" integer, "notes" text, "orgUnitId" uuid, "propertyId" uuid NOT NULL, "unitId" uuid, "lesseeId" uuid NOT NULL, CONSTRAINT "PK_2668e338ab2d27079170ea55ea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c991cff48251baf7ce5037bc2" ON "leases" ("lease_number") `);
        await queryRunner.query(`CREATE TYPE "public"."properties_status_enum" AS ENUM('AVAILABLE', 'LEASED', 'SUSPENDED', 'REDEVELOPMENT')`);
        await queryRunner.query(`CREATE TABLE "properties" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "property_code" character varying(128) NOT NULL, "name" character varying(255) NOT NULL, "address" jsonb, "region" character varying(128) NOT NULL, "district" character varying(128) NOT NULL, "parcel_number" character varying(64), "land_use" character varying(128), "area_sqm" numeric, "status" "public"."properties_status_enum" NOT NULL DEFAULT 'AVAILABLE', "orgUnitId" uuid, CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31731419d43422c82ef98fb1ac" ON "properties" ("property_code") `);
        await queryRunner.query(`CREATE TYPE "public"."org_units_type_enum" AS ENUM('NATIONAL', 'REGION', 'DISTRICT', 'UNIT')`);
        await queryRunner.query(`CREATE TABLE "org_units" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(64) NOT NULL, "name" character varying(255) NOT NULL, "type" "public"."org_units_type_enum" NOT NULL, "parentId" uuid, CONSTRAINT "PK_b4a19b7f3756560cd75643be5a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5382611e999b45b0e98a7859c7" ON "org_units" ("code") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(128) NOT NULL, "description" text, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dad765629e83229da6feda1c1" ON "permissions" ("code") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "roleId" uuid, "permissionId" uuid, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "description" text, "min_rank_required" integer NOT NULL, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "phone" character varying(32), "password" text NOT NULL, "first_name" character varying(128) NOT NULL, "last_name" character varying(128) NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "rank_level" integer NOT NULL, "last_login_at" TIMESTAMP WITH TIME ZONE, "orgUnitId" uuid, "roleId" uuid NOT NULL, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "oauth_clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "client_id" character varying(255) NOT NULL, "client_secret" character varying(255) NOT NULL, "grant_types" text array NOT NULL, "redirect_uris" text array, "first_party" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_c5c4af500cc8bfc05500fff7f90" UNIQUE ("client_id"), CONSTRAINT "PK_c4759172d3431bae6f04e678e0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "device_info" jsonb, "ip_address" character varying(64), "last_seen_at" TIMESTAMP WITH TIME ZONE, "revoked" boolean NOT NULL DEFAULT false, "userId" uuid NOT NULL, "oauthClientId" uuid, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric NOT NULL, "paymentId" uuid, "invoiceId" uuid, CONSTRAINT "PK_a5c6ff22065ac772620c85f4efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lease_autopay_prefs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "autopay_enabled" boolean NOT NULL DEFAULT false, "autopay_day" integer, "leaseId" uuid, "mandateId" uuid, CONSTRAINT "PK_283e15dbf11827d86ac49df7f09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dunning_rules" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "first_reminder_days" integer NOT NULL, "second_reminder_days" integer NOT NULL, "final_notice_days" integer NOT NULL, "late_fee_percent" numeric, "orgUnitId" uuid NOT NULL, CONSTRAINT "PK_7dce8092cd1d117f5bde979add3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_type_enum" AS ENUM('BILLING_GENERATE', 'AUTOPAY_CAPTURE', 'DUNNING_SEND')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum" AS ENUM('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "jobs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."jobs_type_enum" NOT NULL, "payload" jsonb NOT NULL, "run_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."jobs_status_enum" NOT NULL DEFAULT 'QUEUED', "last_error" text, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."dunning_events_stage_enum" AS ENUM('FIRST', 'SECOND', 'FINAL', 'LEGAL')`);
        await queryRunner.query(`CREATE TYPE "public"."dunning_events_channel_enum" AS ENUM('SMS', 'EMAIL', 'PUSH', 'LETTER')`);
        await queryRunner.query(`CREATE TYPE "public"."dunning_events_status_enum" AS ENUM('SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "dunning_events" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stage" "public"."dunning_events_stage_enum" NOT NULL, "event_at" TIMESTAMP WITH TIME ZONE NOT NULL, "channel" "public"."dunning_events_channel_enum" NOT NULL, "status" "public"."dunning_events_status_enum" NOT NULL, "details" jsonb, "invoiceId" uuid NOT NULL, CONSTRAINT "PK_3900bfbc2523fb0190bb5d500e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_links_target_type_enum" AS ENUM('LEASE', 'INVOICE', 'PAYMENT', 'MANDATE')`);
        await queryRunner.query(`CREATE TABLE "job_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_type" "public"."job_links_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "jobId" uuid, CONSTRAINT "PK_3bcec2da3899a4883b7af2dd342" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1e1a9980c608874728d8238b6" ON "job_links" ("target_id") `);
        await queryRunner.query(`CREATE TYPE "public"."adjustments_type_enum" AS ENUM('CREDIT_NOTE', 'DEBIT_NOTE', 'REFUND')`);
        await queryRunner.query(`CREATE TYPE "public"."adjustments_status_enum" AS ENUM('PENDING', 'APPROVED', 'POSTED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "adjustments" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."adjustments_type_enum" NOT NULL, "amount" numeric NOT NULL, "reason" character varying(255), "status" "public"."adjustments_status_enum" NOT NULL DEFAULT 'PENDING', "invoiceId" uuid, "paymentId" uuid, "createdById" uuid, CONSTRAINT "PK_9236bf670736e5ad5df36dd1eb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."approvals_target_type_enum" AS ENUM('LEASE', 'INVOICE', 'REFUND', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."approvals_state_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "approvals" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_type" "public"."approvals_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "state" "public"."approvals_state_enum" NOT NULL DEFAULT 'PENDING', "decided_at" TIMESTAMP WITH TIME ZONE, "remarks" text, "requestedById" uuid NOT NULL, "decidedById" uuid, CONSTRAINT "PK_690417aaefa84d18b1a59e2a499" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39e52ec73eee67074b5fe5e7d7" ON "approvals" ("target_id") `);
        await queryRunner.query(`CREATE TABLE "ad_hoc_bills" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying(512) NOT NULL, "amount" numeric NOT NULL, "tax_amount" numeric, "approved" boolean NOT NULL DEFAULT false, "approved_at" TIMESTAMP WITH TIME ZONE, "leaseId" uuid NOT NULL, "raisedById" uuid NOT NULL, "approvedById" uuid, CONSTRAINT "PK_82740b052a3c804ad79658552a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ad_hoc_bill_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adHocBillId" uuid, "invoiceId" uuid, CONSTRAINT "PK_086fea15d709b595d4a97e0b889" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_recipient_type_enum" AS ENUM('PARTY', 'USER')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('SMS', 'EMAIL', 'PUSH', 'INAPP')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('QUEUED', 'SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_type" "public"."notifications_recipient_type_enum" NOT NULL, "recipient_id" uuid NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "template_code" character varying(128) NOT NULL, "payload" jsonb NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'QUEUED', "sent_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5332a4daa46fd3f4e6625dd275" ON "notifications" ("recipient_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying(128) NOT NULL, "entity_type" character varying(128) NOT NULL, "entity_id" uuid NOT NULL, "before" jsonb, "after" jsonb, "actorUserId" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85c204d8e47769ac183b32bf9c" ON "audit_logs" ("entity_id") `);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD CONSTRAINT "FK_7c857d21e12e81fd6ce8585d057" FOREIGN KEY ("webhookId") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_units" ADD CONSTRAINT "FK_99e3f071b6c5b3c50e712534bee" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_5aad3bc717a4f483887ec61dbc8" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_da53bc3356720fd3f80ce88fcb0" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_contacts" ADD CONSTRAINT "FK_51c501cb13820a4f951c061cdae" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD CONSTRAINT "FK_59563b937288f7720d955dd3967" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_a25d33dbd8e95a1875d42ac40c3" FOREIGN KEY ("providerId") REFERENCES "payment_providers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_42776623fc37a3833e6943c49bf" FOREIGN KEY ("payerPartyId") REFERENCES "parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_62c5af9253d7d4d993c46fd1677" FOREIGN KEY ("receiverOrgUnitId") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" ADD CONSTRAINT "FK_24226b2b0892b4ee16e637f91ca" FOREIGN KEY ("reconciliationId") REFERENCES "reconciliations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" ADD CONSTRAINT "FK_ce62567a174c09dab3432e285df" FOREIGN KEY ("matchedPaymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD CONSTRAINT "FK_df70443fee08c1e59d749b4a56b" FOREIGN KEY ("providerId") REFERENCES "payment_providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mandates" ADD CONSTRAINT "FK_0e3e017acd098c3e980f4ec2990" FOREIGN KEY ("partyId") REFERENCES "parties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mandates" ADD CONSTRAINT "FK_7fd88e21bf86411f7de6bd3562e" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mandates" ADD CONSTRAINT "FK_16af1b0c62a3e97f36d7986077b" FOREIGN KEY ("providerId") REFERENCES "payment_providers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charges" ADD CONSTRAINT "FK_880915c7f539e1734fc5de5ea09" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_runs" ADD CONSTRAINT "FK_d3f8d2dfac6f01812e04d1613f6" FOREIGN KEY ("orgUnitId") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_runs" ADD CONSTRAINT "FK_ecc3c8c405e53272787324972fc" FOREIGN KEY ("initiatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_9f57f31e620fe759b452feb776e" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5d23ee470b8586b7dd9c3c01894" FOREIGN KEY ("billingRunId") REFERENCES "billing_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_d918bd7dff03a43f8e0dc8ed939" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leases" ADD CONSTRAINT "FK_ed0c3b18896e4f7b68da5c400e0" FOREIGN KEY ("orgUnitId") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leases" ADD CONSTRAINT "FK_f7abdef0af12d69bdcb85f89493" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leases" ADD CONSTRAINT "FK_41ddb25063485103a828efc4084" FOREIGN KEY ("unitId") REFERENCES "property_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leases" ADD CONSTRAINT "FK_a3ee8561d88ea727814fda471a7" FOREIGN KEY ("lesseeId") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_553b2e2d4c464eb164904050ea3" FOREIGN KEY ("orgUnitId") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "org_units" ADD CONSTRAINT "FK_b9877181917509f8c6f25bc2ea9" FOREIGN KEY ("parentId") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_497156903169d074a77f31c8480" FOREIGN KEY ("orgUnitId") REFERENCES "org_units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_a23208dae7d5405e42c49e661a7" FOREIGN KEY ("oauthClientId") REFERENCES "oauth_clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_68129272bde8768a20d6967a62c" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_6ef3658d2831bd99e2f848d55a9" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" ADD CONSTRAINT "FK_6042e7bdc75207ebeee0b2f5fc4" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" ADD CONSTRAINT "FK_eb56bcf1a16eb3fb6e51dfb621e" FOREIGN KEY ("mandateId") REFERENCES "mandates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dunning_rules" ADD CONSTRAINT "FK_d952eea0ed2ed89014c652ba0e4" FOREIGN KEY ("orgUnitId") REFERENCES "org_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dunning_events" ADD CONSTRAINT "FK_382d1a857a3e92d55e80cf5dac1" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_links" ADD CONSTRAINT "FK_f3235187d1d5bc618b791c0094a" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustments" ADD CONSTRAINT "FK_6172c5923cdb1e5f0352f5e1e33" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustments" ADD CONSTRAINT "FK_6aa615aac68a2c513ca67549384" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustments" ADD CONSTRAINT "FK_adc34c271cf67e6ac29ba9e913b" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_03ae6a86f1f8dbe0ab8505f6907" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_88e6d43584d92b367d0124ef453" FOREIGN KEY ("decidedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" ADD CONSTRAINT "FK_62ae560b97c02ecb8e319d9fea4" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" ADD CONSTRAINT "FK_a418cabb1d77844c5173c8cf006" FOREIGN KEY ("raisedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" ADD CONSTRAINT "FK_3d1721046245f00a18bc6efdf62" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" ADD CONSTRAINT "FK_3968b02ded2a49059944dcd5afe" FOREIGN KEY ("adHocBillId") REFERENCES "ad_hoc_bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" ADD CONSTRAINT "FK_37907e7ae20cdc001f187c26952" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_e36d23e1e7cf81ea77758bef795" FOREIGN KEY ("actorUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_e36d23e1e7cf81ea77758bef795"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" DROP CONSTRAINT "FK_37907e7ae20cdc001f187c26952"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bill_links" DROP CONSTRAINT "FK_3968b02ded2a49059944dcd5afe"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" DROP CONSTRAINT "FK_3d1721046245f00a18bc6efdf62"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" DROP CONSTRAINT "FK_a418cabb1d77844c5173c8cf006"`);
        await queryRunner.query(`ALTER TABLE "ad_hoc_bills" DROP CONSTRAINT "FK_62ae560b97c02ecb8e319d9fea4"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_88e6d43584d92b367d0124ef453"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_03ae6a86f1f8dbe0ab8505f6907"`);
        await queryRunner.query(`ALTER TABLE "adjustments" DROP CONSTRAINT "FK_adc34c271cf67e6ac29ba9e913b"`);
        await queryRunner.query(`ALTER TABLE "adjustments" DROP CONSTRAINT "FK_6aa615aac68a2c513ca67549384"`);
        await queryRunner.query(`ALTER TABLE "adjustments" DROP CONSTRAINT "FK_6172c5923cdb1e5f0352f5e1e33"`);
        await queryRunner.query(`ALTER TABLE "job_links" DROP CONSTRAINT "FK_f3235187d1d5bc618b791c0094a"`);
        await queryRunner.query(`ALTER TABLE "dunning_events" DROP CONSTRAINT "FK_382d1a857a3e92d55e80cf5dac1"`);
        await queryRunner.query(`ALTER TABLE "dunning_rules" DROP CONSTRAINT "FK_d952eea0ed2ed89014c652ba0e4"`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" DROP CONSTRAINT "FK_eb56bcf1a16eb3fb6e51dfb621e"`);
        await queryRunner.query(`ALTER TABLE "lease_autopay_prefs" DROP CONSTRAINT "FK_6042e7bdc75207ebeee0b2f5fc4"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_6ef3658d2831bd99e2f848d55a9"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_68129272bde8768a20d6967a62c"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_a23208dae7d5405e42c49e661a7"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_497156903169d074a77f31c8480"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "org_units" DROP CONSTRAINT "FK_b9877181917509f8c6f25bc2ea9"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_553b2e2d4c464eb164904050ea3"`);
        await queryRunner.query(`ALTER TABLE "leases" DROP CONSTRAINT "FK_a3ee8561d88ea727814fda471a7"`);
        await queryRunner.query(`ALTER TABLE "leases" DROP CONSTRAINT "FK_41ddb25063485103a828efc4084"`);
        await queryRunner.query(`ALTER TABLE "leases" DROP CONSTRAINT "FK_f7abdef0af12d69bdcb85f89493"`);
        await queryRunner.query(`ALTER TABLE "leases" DROP CONSTRAINT "FK_ed0c3b18896e4f7b68da5c400e0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_d918bd7dff03a43f8e0dc8ed939"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5d23ee470b8586b7dd9c3c01894"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_9f57f31e620fe759b452feb776e"`);
        await queryRunner.query(`ALTER TABLE "billing_runs" DROP CONSTRAINT "FK_ecc3c8c405e53272787324972fc"`);
        await queryRunner.query(`ALTER TABLE "billing_runs" DROP CONSTRAINT "FK_d3f8d2dfac6f01812e04d1613f6"`);
        await queryRunner.query(`ALTER TABLE "lease_charges" DROP CONSTRAINT "FK_880915c7f539e1734fc5de5ea09"`);
        await queryRunner.query(`ALTER TABLE "mandates" DROP CONSTRAINT "FK_16af1b0c62a3e97f36d7986077b"`);
        await queryRunner.query(`ALTER TABLE "mandates" DROP CONSTRAINT "FK_7fd88e21bf86411f7de6bd3562e"`);
        await queryRunner.query(`ALTER TABLE "mandates" DROP CONSTRAINT "FK_0e3e017acd098c3e980f4ec2990"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP CONSTRAINT "FK_df70443fee08c1e59d749b4a56b"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" DROP CONSTRAINT "FK_ce62567a174c09dab3432e285df"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_lines" DROP CONSTRAINT "FK_24226b2b0892b4ee16e637f91ca"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_62c5af9253d7d4d993c46fd1677"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_42776623fc37a3833e6943c49bf"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_a25d33dbd8e95a1875d42ac40c3"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP CONSTRAINT "FK_59563b937288f7720d955dd3967"`);
        await queryRunner.query(`ALTER TABLE "party_contacts" DROP CONSTRAINT "FK_51c501cb13820a4f951c061cdae"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_da53bc3356720fd3f80ce88fcb0"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_5aad3bc717a4f483887ec61dbc8"`);
        await queryRunner.query(`ALTER TABLE "property_units" DROP CONSTRAINT "FK_99e3f071b6c5b3c50e712534bee"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP CONSTRAINT "FK_7c857d21e12e81fd6ce8585d057"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85c204d8e47769ac183b32bf9c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5332a4daa46fd3f4e6625dd275"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_recipient_type_enum"`);
        await queryRunner.query(`DROP TABLE "ad_hoc_bill_links"`);
        await queryRunner.query(`DROP TABLE "ad_hoc_bills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39e52ec73eee67074b5fe5e7d7"`);
        await queryRunner.query(`DROP TABLE "approvals"`);
        await queryRunner.query(`DROP TYPE "public"."approvals_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approvals_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "adjustments"`);
        await queryRunner.query(`DROP TYPE "public"."adjustments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adjustments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1e1a9980c608874728d8238b6"`);
        await queryRunner.query(`DROP TABLE "job_links"`);
        await queryRunner.query(`DROP TYPE "public"."job_links_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "dunning_events"`);
        await queryRunner.query(`DROP TYPE "public"."dunning_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."dunning_events_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."dunning_events_stage_enum"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_type_enum"`);
        await queryRunner.query(`DROP TABLE "dunning_rules"`);
        await queryRunner.query(`DROP TABLE "lease_autopay_prefs"`);
        await queryRunner.query(`DROP TABLE "payment_allocations"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "oauth_clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dad765629e83229da6feda1c1"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5382611e999b45b0e98a7859c7"`);
        await queryRunner.query(`DROP TABLE "org_units"`);
        await queryRunner.query(`DROP TYPE "public"."org_units_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31731419d43422c82ef98fb1ac"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP TYPE "public"."properties_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c991cff48251baf7ce5037bc2"`);
        await queryRunner.query(`DROP TABLE "leases"`);
        await queryRunner.query(`DROP TYPE "public"."leases_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leases_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37669c562a2525929927d9d691"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP TABLE "billing_runs"`);
        await queryRunner.query(`DROP TYPE "public"."billing_runs_run_type_enum"`);
        await queryRunner.query(`DROP TABLE "lease_charges"`);
        await queryRunner.query(`DROP TYPE "public"."lease_charges_frequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79a3477ecd27e3364b4c23f298"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_109010e7cbb22421bb4bf32b94"`);
        await queryRunner.query(`DROP TABLE "parties"`);
        await queryRunner.query(`DROP TYPE "public"."parties_type_enum"`);
        await queryRunner.query(`DROP TABLE "mandates"`);
        await queryRunner.query(`DROP TYPE "public"."mandates_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b92bdeea5c610e84052154ef2"`);
        await queryRunner.query(`DROP TABLE "payment_providers"`);
        await queryRunner.query(`DROP TABLE "reconciliations"`);
        await queryRunner.query(`DROP TYPE "public"."reconciliations_status_enum"`);
        await queryRunner.query(`DROP TABLE "reconciliation_lines"`);
        await queryRunner.query(`DROP TYPE "public"."reconciliation_lines_match_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0942ab806143ef6a2c888dce03"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_type_enum"`);
        await queryRunner.query(`DROP TABLE "party_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_888a4852e27627d1ebd8a094e9"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_owner_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fb0cc1f34e30369e6226bef5a"`);
        await queryRunner.query(`DROP TABLE "property_units"`);
        await queryRunner.query(`DROP TYPE "public"."property_units_status_enum"`);
        await queryRunner.query(`DROP TABLE "webhook_events"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_events_status_enum"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
    }

}
