const NOTIFICATION_DATA = [
  {
    id: "1",
    name: "Rent Due Reminder",
    username: "@Landlord",
    date: "01 Sep",
    content: "Your land rent for Plot A-23 is due on 5th September. Please ensure timely payment to avoid penalties.",
    type: "Reminder",
    from: "Personal",
    image: require('assets/m9.jpg'),
  },
  {
    id: "2",
    name: "System Maintenance Notice",
    username: "@LandRentSystem",
    date: "31 Aug",
    content: "The online rent payment portal will be unavailable from 2 AM to 6 AM for scheduled maintenance.",
    type: "Emergency",
    from: "System",
    image: null,
  },
  {
    id: "3",
    name: "New Rent Policy Update",
    username: "@LandAuthority",
    date: "30 Aug",
    content: "A new rent policy for agricultural plots will take effect from 15th September. Check the portal for details.",
    type: "Update",
    from: "System",
    image: require('assets/m4.jpg'),
  },
  {
    id: "4",
    name: "Payment Confirmation",
    username: "@LandRentSystem",
    date: "29 Aug",
    content: "We have received your payment for Plot B-14. Thank you for completing your transaction on time.",
    type: "Confirmation",
    from: "Personal",
    image: null,
  },
  {
    id: "5",
    name: "Rent Increase Alert",
    username: "@LandAuthority",
    date: "28 Aug",
    content: "Annual land rent for residential plots will increase by 5% starting from October. Please review the updated rates.",
    type: "Alert",
    from: "System",
    image: require('assets/m5.jpg'),
  },
];

export default NOTIFICATION_DATA;
